name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Verify module
        run: go mod tidy && git diff --exit-code || (echo 'Run go mod tidy locally' && exit 1)
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
      - name: Race tests (core packages)
        run: go test -race ./internal/... || true
